
### Подобрать подходящую ячейку
POST http://localhost:8080/api/postamat/suitableCell
Content-Type: application/json

{
  "parcelDimensions": [
    {
      "unit": "cm",
      "scale": "ABSOLUTE",
      "value": 30
    },
    {
      "unit": "cm",
      "scale": "ABSOLUTE",
      "value": 20
    },
    {
      "unit": "cm",
      "scale": "ABSOLUTE",
      "value": 10
    }
  ]
}

### Получить общий объем постамата
GET http://localhost:8080/api/postamat/volume
Content-Type: application/json