
### Подобрать подходящую ячейку
POST http://localhost:8080/api/postamat/suitableCells
Content-Type: application/json

{
  "parcelDimensions": [
    {
      "unit": "cm",
      "scale": "ABSOLUTE",
      "value": 10
    },
    {
      "unit": "cm",
      "scale": "ABSOLUTE",
      "value": 20
    },
    {
      "unit": "cm",
      "scale": "ABSOLUTE",
      "value": 30
    }
  ]
}

### Получить общий объем постамата
GET http://localhost:8080/api/postamat/volume
Accept-Language: ja-JP
Content-Type: application/json

### Получить объемный вес
GET http://localhost:8080/api/postamat/volumeWeight
Content-Type: application/json